service: ucits-bot

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: eu-west-3
  environment:
    REGION: ${env:REGION}
    SECRET_NAME: ${env:SECRET_NAME}
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_MAIN: ${env:DB_MAIN}

  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:SUBNET_1}
      - ${env:SUBNET_2}
      - ${env:SUBNET_3}

functions:
  updateFunds:
    handler: handler.update_funds
  
  updatePerformance:
    handler: handler.update_performance
  
  initDb:
    handler: handler.init_db

plugins:
  - serverless-offline
  - serverless-python-requirements
 
custom:
  pythonRequirements:
    dockerizePip: non-linux

package:
  exclude:
    - venv/**