name: UCITSBot Update

on:
  push:
    branches:
      - master
    paths:
      - ucits-bot/**
  workflow_dispatch:

defaults:
  run:
    working-directory: ucits-bot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
  
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: npm ci

      - name: Deploy Lambdas
        uses: serverless/github-action@v3.1
        with:
          args: -c "cd ./ucits-bot && serverless deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          REGION: ${{ secrets.REGION }}
          SECRET_NAME: ${{ secrets.SECRET_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_MAIN: ${{ secrets.DB_MAIN }}
          SECURITY_GROUP_ID: ${{ secrets.SECURITY_GROUP_ID }}
          SUBNET_1: ${{ secrets.SUBNET_1 }}
          SUBNET_2: ${{ secrets.SUBNET_2 }}
          SUBNET_3: ${{ secrets.SUBNET_3 }}
          
